import Head from 'next/head'

export default function Login() {
    return (
        <>
            <Head>
                <title>Borges Car - Conta</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='h-screen w-screen bg-[#6e97ae] flex items-center justify-center'>
                <div className='w-2/6 h-5/6 bg-white rounded-3xl flex flex-col justify-around'>
                    <div className='w-40 h-40 bg-gray-800 rounded-full mt-2 self-center'></div>

                    <div className='h-1/3 flex flex-col px-10'>
                        <label htmlFor="email" className='font-bold'>E-MAIL</label>
                        <input type="text" id='email' className='bg-[#6F87C5] border-none outline-0 p-2 rounded mb-5' />
                        <label htmlFor="pass" className='font-bold'>SENHA</label>
                        <input type="text" id='pass' className='bg-[#6F87C5] border-none outline-0 p-2 rounded' />
                    </div>

                    <button className='bg-[#6F87C5] text-white font-bold font-3xl w-1/2 p-2 self-center c-pointer '>ENTRAR</button>
                </div>
            </main>
        </>
    )
}
