import Head from 'next/head'
import Image from 'next/image'

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Logos from '@/components/Logos'

import carImage from '../../public/assets/cars/aston.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Borges Car</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen overflow-x-hidden'>
        <Header />
        <div className='w-full my-10 flex justify-center gap-10'>
          <Logos />
        </div>
        <div className="h-full bg-gray-200 w-full">
          <Image
            src={carImage}
            alt="Aston Martin"
            className='w-full h-full'
          />
        </div>
        <Footer />
      </main>
    </>
  )
}
